### ISSUE TITLE
UnobservedTaskException - version 1.6.1

### ISSUE THREAD

**Issue by NivTikolski** [neo4j/neo4j-dotnet-driver#312] opened 2018-07-26 13:56 UTC
i have a problem with the new driver. 
we have cluster(3 instances), neo4j 3.4.4. current dotnet driver 1.5.2
when i upload our's code with the new driver version we get this error:

UnobservedTaskException detected:
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Web.ThreadContext.AssociateWithCurrentThread(Boolean setImpersonationContext)
   at System.Web.HttpApplication.OnThreadEnterPrivate(Boolean setImpersonationContext)
   at System.Web.HttpApplication.System.Web.Util.ISyncContext.Enter()
   at System.Web.Util.SynchronizationHelper.SafeWrapCallback(Action action)
   at System.Threading.Tasks.Task.Execute()

when i downgrade back to 1.5.2 everyhing works well.

thanks,
Niv.

**Comment by zhenlineo** [comment] 2018-07-27 08:20
Hi @NivTikolski,

Could you give us more information of how you used the driver in your code? Do you have some example code to reproduce this error?

The stacktrace you give is a bit too general for me to understand the possible causes.
For example, I am not sure which object is null and how you used the object in your application. 
Also what .net framework your application is running, what methods you called etc.

Cheers,
Zhen

**Comment by NivTikolski** [comment] 2018-07-27 12:14
@zhenlineo 
i know the stack trace is general because its not coming from our code, this is the stacktrace the delegate caught.
.net 4.6.1
i tried to reproduce it, i have no idea how, i just know that the same code works with 1.5.2 and not working with 1.6.1
how i use the driver? i show you some samples of code:
```

public async Task<Profile> Get(Guid public_user_id)
{
            return await Read(async session =>
            {
                var query = $@"MATCH (p:Profile) 
WHERE p.public_user_id = '{public_user_id.ToString().ToUpper()}'
WITH p
OPTIONAL MATCH (p)-[r:{nameof(Relations.Follow)}]->(f: Profile)
WITH p, count(r) AS followings_count
OPTIONAL MATCH(p)<-[r:{nameof(Relations.Follow)}]-(f:Profile)
WITH p, followings_count, count(r) AS followers_count
OPTIONAL MATCH(p)-[r]->(feeditem: FeedItem) 
WHERE type(r) STARTS WITH 'SourceProfile' AND (feeditem.status = 0 OR feeditem.status = 6)
RETURN p, followings_count, followers_count, count(r) AS post_count";

                return (await (await session.RunAsync(query)).ToListAsync(p =>
                {
                    var profile = p["p"].As<INode>().To<Profile>();

                    profile.post_count = p["post_count"].As<int>();
                    profile.followers_count = p["followers_count"].As<int>();
                    profile.followings_count = p["followings_count"].As<int>();

                    return profile;

                })).FirstOrDefault();
            });
        }
```


the read function:
```
protected async Task<T> Read<T>(Func<IStatementRunner, Task<T>> reader)
 {
            try
            {
                var session = driver.Session(AccessMode.Read);
                try
                {
                    return await session.ReadTransactionAsync(async transaction =>
                    {
                        return await reader(transaction);
                    });
                }
                finally
                {
                    await session.CloseAsync();
                }
            }
            catch (Exception ex)
            {
                Logger.Log.Error(ex);
                return default(T);
            }
}
```

i keep trying to reproduce it, but i hope you can look and think what can cause that problem.

**Comment by ali-ince** [comment] 2018-07-31 07:16
@NivTikolski Could you please set an event handler for `UnobservedTaskException` through `TaskScheduler.UnobservedTaskException`? This will provide more valuable information about the root cause of the error.

Thanks.

**Comment by NivTikolski** [comment] 2018-07-31 07:27
@ali-ince 
i have this...
in global.asax.cs at the application start:
`TaskScheduler.UnobservedTaskException += TaskScheduler_UnobservedTaskException;`

```
private void TaskScheduler_UnobservedTaskException(object sender, UnobservedTaskExceptionEventArgs e)
        {
            e.SetObserved();
            e.Exception.Handle(ex =>
            {
                Logger.Log.Error("UnobservedTaskException detected:", ex);
                return true;
            });
        }

```

and the error i added is from here. believe me i tried everything i know to get more information about the error, nothing tells me from where it is or what cause it. 
if you have any idea how to get more information i will be happy to hear.

**Comment by NivTikolski** [comment] 2018-08-06 07:15
@ali-ince 
@zhenlineo 
i solved the issue, i don't know exactly where is the problem with 1.6.1 driver but it is something with the changes of the ConfigureAwait(false) you did from 1.5.2

i add to the start of our Read/Write functions `await Task.Delay(1).ConfigureAwait(false)`  and it solved the problem, i think you need to think why it happens and dive deep to this, because i think it will happen to many developers that will try upload this driver to production.


edit:
the problem solved but it caused other problem. performance problem, all our methods now timeX2

you have an idea how to solve the unobserved issue?

**Comment by xied75** [comment] 2018-08-07 13:49
If the big change between 1.6.1 and 1.5.2 is indeed the usage of ```ConfigureAwait(false)```, then it might explain the exception, since the OP is running this within a ASP.NET framework, and the threading model is different here. 

https://msdn.microsoft.com/en-us/magazine/gg598924.aspx
http://blog.stephencleary.com/2012/07/dont-block-on-async-code.html

**Comment by ali-ince** [comment] 2018-08-09 22:52
Hi @NivTikolski,

`UnobservedTaskException` is only thrown when the unobserved task with failure is garbage collected, so it heavily depends on how garbage collector behaves. It is even possible that the event handler is not called, although an exception is thrown but the task is still referenced (which prevents it from garbage collected). This behaviour and the fact that the stack trace doesn't include much useful information makes the diagnosis of the problem almost impossible.

Is it possible that you run into a scenario described [here](https://stackoverflow.com/a/20365859)? If this is not the case, could you please try to reproduce the problem by tweaking your code similar to what is shown [here](https://stackoverflow.com/a/3284286)?

Thanks.

**Comment by NivTikolski** [comment] 2018-08-13 10:59
@ali-ince 
hi,
i couldn't reproduce it on my QA enviroment.
it is only reproduced on Production, i tried many things, for now we upload the driver with a little change in it, and it solved.
we take dmp file from the sever, and when the unobserved task exception happened we saw that the problem is from the TcpSocketClient(the ConnectSocketAsync function). i add `await Task.Delay(1).ConfigureAwait(false);` at the start of the function and like that the problem solved. 
we worked on it about 3 weeks to find a some solution. that's the best we can find, i think from here you should how to fix it.(see the difference in the ConnectSocketAsync between 1.5.2 to 1.6.1,)

Niv.

**Comment by ali-ince** [comment] 2018-08-21 09:40
Hi @NivTikolski,

Unfortunately we're not able to reproduce this error on our side and couldn't see a major difference that would lead to the problem in `TcpSocketClient` as you suggested.

The exception happens on finalizer (on task objects that get garbage collected) so I suspect any active stack trace that you would see on the dump file would be a pointer. 

If you could provide more information (logs and/or dmp files) and ideally a reproduction of the issue - we would be glad to help on this. 

Thanks.

**Comment by NivTikolski** [comment] 2018-08-21 10:33
as i said, if i ass something more for you i would give that of course. we waste our time too much on that already, we using for now a custom driver dll with the fix i wrote the comment before. 
i gave the function that cause the issue, from here i cant find nothing more :\

thanks.

**Comment by technige** [comment] 2019-01-28 09:50
@NivTikolski We've not been able to reproduce the issue you see. Would you be able to provide us with a minimal piece of code that can demonstrate the error for us, please?

**Comment by technige** [comment] 2019-04-25 09:29
Closing as unable to reproduce.

**Closed as completed by technige** 2019-04-25 09:29 UTC
