### ISSUE TITLE
Connection with the server breaks due to IOException: Failed to connect to the server localhost:7687 within connection timeout 5000ms 

### ISSUE THREAD

**Issue by AviAvni** [neo4j/neo4j-dotnet-driver#212] opened 2017-08-06 15:20 UTC
I found that when our webapi server hosted in iis is recycled then we have this error
We use the 1.3 driver
```
Neo4j.Driver.V1.ServiceUnavailableException: Connection with the server breaks due to IOException: Failed to connect to the server localhost:7687 within connection timeout 5000ms ---> System.IO.IOException: Failed to connect to the server localhost:7687 within connection timeout 5000ms
   at Neo4j.Driver.Internal.Connector.SocketConnection.Init() in Z:\BuildAgent\work\9ae188c903d07190\Neo4j.Driver\Neo4j.Driver\Internal\Connector\SocketConnection.cs:line 73
   at Neo4j.Driver.Internal.Connector.DelegatedConnection.Init() in Z:\BuildAgent\work\9ae188c903d07190\Neo4j.Driver\Neo4j.Driver\Internal\Connector\DelegatedConnection.cs:line 96
   --- End of inner exception stack trace ---
   at Neo4j.Driver.Internal.Connector.PooledConnection.OnError(Exception error) in Z:\BuildAgent\work\9ae188c903d07190\Neo4j.Driver\Neo4j.Driver\Internal\Connector\PooledConnection.cs:line 75
   at Neo4j.Driver.Internal.Connector.DelegatedConnection.Init() in Z:\BuildAgent\work\9ae188c903d07190\Neo4j.Driver\Neo4j.Driver\Internal\Connector\DelegatedConnection.cs:line 98
   at Neo4j.Driver.Internal.ConnectionPool.CreateNewPooledConnection() in Z:\BuildAgent\work\9ae188c903d07190\Neo4j.Driver\Neo4j.Driver\Internal\ConnectionPool.cs:line 113
   at Neo4j.Driver.Internal.ConnectionPool.<Acquire>b__21_0() in Z:\BuildAgent\work\9ae188c903d07190\Neo4j.Driver\Neo4j.Driver\Internal\ConnectionPool.cs:line 143
   at Neo4j.Driver.Internal.LoggerBase.TryExecute[T](Func`1 func) in Z:\BuildAgent\work\9ae188c903d07190\Neo4j.Driver\Neo4j.Driver\Internal\LoggerBase.cs:line 49
2017-08-06 15:03:47,502 ERROR ITECH_ApiServices [#32] - Neo4j.Driver.V1.ServiceUnavailableException: Connection with the server breaks due to IOException: Failed to connect to the server localhost:7687 within connection timeout 5000ms ---> System.IO.IOException: Failed to connect to the server localhost:7687 within connection timeout 5000ms
   at Neo4j.Driver.Internal.Connector.SocketConnection.Init() in Z:\BuildAgent\work\9ae188c903d07190\Neo4j.Driver\Neo4j.Driver\Internal\Connector\SocketConnection.cs:line 73
   at Neo4j.Driver.Internal.Connector.DelegatedConnection.Init() in Z:\BuildAgent\work\9ae188c903d07190\Neo4j.Driver\Neo4j.Driver\Internal\Connector\DelegatedConnection.cs:line 96
   --- End of inner exception stack trace ---
   at Neo4j.Driver.Internal.Connector.PooledConnection.OnError(Exception error) in Z:\BuildAgent\work\9ae188c903d07190\Neo4j.Driver\Neo4j.Driver\Internal\Connector\PooledConnection.cs:line 75
   at Neo4j.Driver.Internal.Connector.DelegatedConnection.Init() in Z:\BuildAgent\work\9ae188c903d07190\Neo4j.Driver\Neo4j.Driver\Internal\Connector\DelegatedConnection.cs:line 98
   at Neo4j.Driver.Internal.ConnectionPool.CreateNewPooledConnection() in Z:\BuildAgent\work\9ae188c903d07190\Neo4j.Driver\Neo4j.Driver\Internal\ConnectionPool.cs:line 113
   at Neo4j.Driver.Internal.ConnectionPool.<Acquire>b__21_0() in Z:\BuildAgent\work\9ae188c903d07190\Neo4j.Driver\Neo4j.Driver\Internal\ConnectionPool.cs:line 143
   at Neo4j.Driver.Internal.LoggerBase.TryExecute[T](Func`1 func) in Z:\BuildAgent\work\9ae188c903d07190\Neo4j.Driver\Neo4j.Driver\Internal\LoggerBase.cs:line 54
   at Neo4j.Driver.Internal.Session.<>c__DisplayClass14_0.<Run>b__0() in Z:\BuildAgent\work\9ae188c903d07190\Neo4j.Driver\Neo4j.Driver\Internal\Session.cs:line 62
   at Neo4j.Driver.Internal.LoggerBase.TryExecute[T](Func`1 func) in Z:\BuildAgent\work\9ae188c903d07190\Neo4j.Driver\Neo4j.Driver\Internal\LoggerBase.cs:line 49
2017-08-06 15:03:47,502 ERROR ITECH_ApiServices [#32] - Neo4j.Driver.V1.ServiceUnavailableException: Connection with the server breaks due to IOException: Failed to connect to the server localhost:7687 within connection timeout 5000ms ---> System.IO.IOException: Failed to connect to the server localhost:7687 within connection timeout 5000ms
   at Neo4j.Driver.Internal.Connector.SocketConnection.Init() in Z:\BuildAgent\work\9ae188c903d07190\Neo4j.Driver\Neo4j.Driver\Internal\Connector\SocketConnection.cs:line 73
   at Neo4j.Driver.Internal.Connector.DelegatedConnection.Init() in Z:\BuildAgent\work\9ae188c903d07190\Neo4j.Driver\Neo4j.Driver\Internal\Connector\DelegatedConnection.cs:line 96
   --- End of inner exception stack trace ---
   at Neo4j.Driver.Internal.Connector.PooledConnection.OnError(Exception error) in Z:\BuildAgent\work\9ae188c903d07190\Neo4j.Driver\Neo4j.Driver\Internal\Connector\PooledConnection.cs:line 75
   at Neo4j.Driver.Internal.Connector.DelegatedConnection.Init() in Z:\BuildAgent\work\9ae188c903d07190\Neo4j.Driver\Neo4j.Driver\Internal\Connector\DelegatedConnection.cs:line 98
   at Neo4j.Driver.Internal.ConnectionPool.CreateNewPooledConnection() in Z:\BuildAgent\work\9ae188c903d07190\Neo4j.Driver\Neo4j.Driver\Internal\ConnectionPool.cs:line 113
   at Neo4j.Driver.Internal.ConnectionPool.<Acquire>b__21_0() in Z:\BuildAgent\work\9ae188c903d07190\Neo4j.Driver\Neo4j.Driver\Internal\ConnectionPool.cs:line 143
   at Neo4j.Driver.Internal.LoggerBase.TryExecute[T](Func`1 func) in Z:\BuildAgent\work\9ae188c903d07190\Neo4j.Driver\Neo4j.Driver\Internal\LoggerBase.cs:line 54
   at Neo4j.Driver.Internal.Session.<>c__DisplayClass14_0.<Run>b__0() in Z:\BuildAgent\work\9ae188c903d07190\Neo4j.Driver\Neo4j.Driver\Internal\Session.cs:line 62
   at Neo4j.Driver.Internal.LoggerBase.TryExecute[T](Func`1 func) in Z:\BuildAgent\work\9ae188c903d07190\Neo4j.Driver\Neo4j.Driver\Internal\LoggerBase.cs:line 54

```

**Comment by zhenlineo** [comment] 2017-08-07 11:55
Hi,

What do you mean of `when our webapi server hosted in iis is recycled`? Could you describe a bit more about how you see this error in your system?

Is it correct that you have a server which contains a .net driver inside? Then at the first, the server starts and then the driver is created. For a while, the driver is working as expected such as many queries can run successfully? But when or how does the driver stop working? Is this error printed out when your server get disposed? dose the driver also get disposed properly?

Have you tried to increase the timeout time to infinite `TimeSpan.FromMilliseconds(-1)`? Will you still see this error?

Cheers,
Zhen

**Comment by AviAvni** [comment] 2017-08-07 14:50
We have a asp.net webapi server written in c# with neo4j dotnet driver 1.3
And we define 1 static instance of IDriver and every call to the neo4j db we use different session
Regularly the driver is working ok
after iis do the recycle we see that at the moment the new process is up then we have this exception and after that the code work ok
I'll try to look at the timeout you mentioned

**Comment by razbar** [comment] 2017-08-09 08:32
I have the same issue, every recycle for the application pool in IIS generates this error.

**Comment by razbar** [comment] 2017-08-14 08:12
Hi @zhenlineo any updates on this bug?

**Comment by zhenlineo** [comment] 2017-08-14 09:24
@razbar It is on our current work list. We will make sure to keep you updated on this issue.
@AviAvni said that he did not receive this error with our new 1.5 async API. So maybe you would also be interested to try out [1.5.0-alpha01](https://github.com/neo4j/neo4j-dotnet-driver/releases/tag/1.5.0-alpha01).

**Comment by razbar** [comment] 2017-08-14 21:53
@zhenlineo thanks for the update.

I would definitely be delighted to test it but I need async API that supports causal clustering.
Do you have any release date for this?

**Comment by zhenlineo** [comment] 2017-08-18 12:05
@razbar Hi, we've release a new alpha [1.5.0-alpha02](https://github.com/neo4j/neo4j-dotnet-driver/wiki/1.5-changelog#150-alpha02) with full async support for routing driver too. Pls be free to give it a try.

**Comment by zhenlineo** [comment] 2017-11-06 13:43
We think this error was caused by sync over async in 1.3 driver implementation. 1.5 driver fixes this issue by using sync for sync and async for async as long as it is possible. 

In 1.5, if you are on .net standard 1.3, then we recommend to use async driver API. (The socket lib does not provides us a sync impl therefore we have to wrap sync driver API on top of async socket implementation.) If you are on .net framework 4.5.2+, then you are free to choose between sync and async API.

I am closing this issue as I have not heard this issue any more with the 1.5 async API. Please be free to reopen this issue if you encounter this error again.

Cheers,
Zhen

**Closed as completed by zhenlineo** 2017-11-06 13:43 UTC
