### ISSUE TITLE
Big requests do not complete

### ISSUE THREAD

**Issue by juicelink** [neo4j/neo4j-dotnet-driver#250] opened 2017-10-18 10:41 UTC
On my solution if I run:
`session.Run("match(n) return n limit 5000").ToList()`
It works

if I run:
`session.Run("match(n) return n limit 10000").ToList()`
It never completes

It works with 1.5.0-alpha01 (result comes very quickly) but not with the upper versions (final 1.5.0 included).

(test with dotnet core 2 in xunit unit test)

**Comment by ali-ince** [comment] 2017-10-18 12:59
Hi @juicelink,

Just as a quick check, I've executed [this code](https://gist.github.com/ali-ince/cf554c9e1eeba02252236dd59ab3a4a8) successfully on both .NET Framework 4.6.2 and .NET Core 2.0 as a console app.

Can you give us more information about the environment (OS, neo4j server version, whether this code connects to a remote database, etc.) and any specific config options set on Neo4j.Driver? 

Ali

**Comment by juicelink** [comment] 2017-10-18 13:32
Hi @ali-ince,

Neo4j server: 3.2.1
Server os: Windows server 2012 R2
Client OS: Windows 7 Enterprise SP1
Yes the code connects to a remote database

here's my driver initialization:
`GraphDatabase.Driver(
    "bolt://host:port/",
    AuthTokens.Basic("user", "pwd"),
    new Config { EncryptionLevel = EncryptionLevel.None, ConnectionTimeout = ConnectionTimeout(3600)})`

If I use FetchAsync, it returns the first 3000 - 4000 records then it blocks;

**Comment by AviAvni** [comment] 2017-10-25 11:27
Hi we have this problem too from what we debug it's look like this method is the problem
https://github.com/neo4j/neo4j-dotnet-driver/blob/1.5/Neo4j.Driver/Neo4j.Driver/Internal/IO/ChunkReader.cs#L113
we alyays get in the trace that the 'read' variable is 0

**Comment by AviAvni** [comment] 2017-10-25 12:00
sorry it's in https://github.com/neo4j/neo4j-dotnet-driver/blob/1.5/Neo4j.Driver/Neo4j.Driver/Internal/IO/ChunkReader.cs#L166
when ReadAsync is task result is 0 it dosn't stop read from the stream

@zhenlineo please look at this it's blocking us from using 1.5 in production and it makes the cpu to 100%

**Comment by AviAvni** [comment] 2017-10-25 13:16
wrap the code with await session.ReadTransactionAsync(async transaction
solve the issue

**Comment by ali-ince** [comment] 2017-10-25 13:46
Hi,

We’re looking into this issue. @aviavni could you please provide us a code snippet that doesn’t work and works? And I guess you’re on .Net Framework rather than .Net Core, is it correct?

Thanks,

Ali

**Comment by AviAvni** [comment] 2017-10-26 08:04
@ali-ince 
Yes working on .Net Framework

dosent work
```
var session = driver.Session(AccessMode.Read);
try
{
    return await (await session.RunAsync(query)).ToListAsync();
}
finally
{
    await session.CloseAsync();
}
```

work
```
var session = driver.Session(AccessMode.Read);
try
{
    return await session.ReadTransactionAsync(async transaction =>
    {
        return await (await session.RunAsync(query)).ToListAsync();
    });
}
finally
{
    await session.CloseAsync();
}
```

same with FetchAsync

**Comment by AviAvni** [comment] 2017-10-26 08:07
also it's a problem that session is IDisposable and use CloseAsync instead of 'using' is preferred
I know that C#8 will bring IAsyncDisposable but till then please provide IAsyncSession interface that
not implement the IDisposable interface

**Comment by zhenlineo** [comment] 2017-10-26 13:07
When the driver got into this infinite read=0 loop, do you got any error on the server side?

We are currently looking into this, but not very sure how to reproduce the error. Do you have this problem to every query you run? Could you give us more hints how to reproduce it? Such as are you using direct driver or routing driver(connect to one db or cluster?) where is your server and where is your client? Anything in the middle? Is your db under a very heavy load? Does the error only happen to certain query after db running for a while etc.

We should definitely handle this 'read=0', at least an error or some timeout, but we would also like to understand why 'read=0' would happen. Thanks in advance for you info. 

Cheers,
Zhen & Ali

**Comment by AviAvni** [comment] 2017-10-26 13:24
@zhenlineo no error only 100% cpu it's happend also in the work snippet
there are times its work and time the infinit loop

we are using routing driver
the server and client(asp web api on iis) are in ec2 instances on amazon
no middle
db not under heavy load
we run the query lots of time sometimes it's not return sometime run success

as I saw in the documentation read = 0 is when the stream is finished

if you can send us patched neo4j dll we can check if it solved it

**Comment by pjeannet** [comment] 2017-10-27 16:07
Hi, I might have encountered something similar. 
I'm sending some `USING PERIODIC COMMIT` query that can take some time to complete (around 10min). In this case code seems to hang up and never receive the result from query (both sync and async code). Is there some timeout hidden under the hook (in the driver or dotnet lib used for REST) that I would not be aware of?
I'm thinking of splitting the sources to import them by smaller chunk but it would be nice to know if there's a limit on query time when using the driver :)

**Comment by juicelink** [comment] 2017-10-27 22:58
Want to precise that I don't have this issue with previous versions. The big queries that before were pretty fast now hang. Nothing (serveur, network, etc..) as changed in my solution except for the neo4j client version. For now I stay with 1.5.0-alpha1, the only I've tested that has async feature and doesn't freeze on big queries. 
Will try to give you more details next days

**Comment by ali-ince** [comment] 2017-10-29 20:35
Hi,

@juicelink We believe that #253 addresses your issue. Will you be able to build a version from this PR and verify if it works for you?

@AviAvni With the same PR #253 (also includes #252) the infinite loop when unexpected end of stream is countered is now addressed. Will you be able to build a version from this PR and verify if it works for you? However, as @zhenlineo already said, the Stream.Read or Stream.ReadAsync returning 0 is a clue for a network layer problem. And for Session's being IDisposable is inherently for backward compatibility and if you need full asynchronicity the preferred approach is similar to your code snippet

```csharp
var session = driver.Session(...);
try {
   // do some work asynchronously 
} finally {
   await session.CloseAsync();
}
```
you can even wrap the whole inside a using block if you would like to. Please note that when `CloseAsync` is explicitly called `Dispose` will not perform any operations at all.

```csharp
using (var session = driver.Session(...))
{
  try {
     // do some work asynchronously
  } finally {
    await session.CloseAsync();
  }
}
```

Cheers.

**Comment by ali-ince** [comment] 2017-10-29 20:42
Hi @pierre-weceipt,

There's not a client-side execution timeout and what you're trying to do should not have any problems at all. Please check #253 if it resolves your problem, verify if your code is correct and also check for any errors on the server logs. Please let us know, if your problem is not resolved.

Thanks.

**Comment by AviAvni** [comment] 2017-10-30 09:45
@ali-ince I compiled the dll and it's solve the 100% cpu please publish new version to nuget

**Comment by pjeannet** [comment] 2017-10-30 13:40
@ali-ince 
Unfortunatly it did not change a thing for me, my query complete on server but result are not sent to the application. I looked into the logs and there's an error timeout :

```
2017-10-30 13:14:20.104+0000 INFO [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by scheduler for time threshold [128534]:  Starting check pointing...
2017-10-30 13:14:20.104+0000 INFO [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by scheduler for time threshold [128534]:  Starting store flush...
2017-10-30 13:14:22.453+0000 INFO [o.n.k.i.s.c.CountsTracker] About to rotate counts store at transaction 128548 to [/var/lib/neo4j/data/databases/graph.db/neostore.counts.db.a], from [/var/lib/neo4j/data/databases/graph.db/neostore.counts.db.b].
2017-10-30 13:14:22.459+0000 INFO [o.n.k.i.s.c.CountsTracker] Successfully rotated counts store at transaction 128548 to [/var/lib/neo4j/data/databases/graph.db/neostore.counts.db.a], from [/var/lib/neo4j/data/databases/graph.db/neostore.counts.db.b].
2017-10-30 13:14:57.588+0000 INFO [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by scheduler for time threshold [128534]:  Store flush completed
2017-10-30 13:14:57.588+0000 INFO [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by scheduler for time threshold [128534]:  Starting appending check point entry into the tx log...
2017-10-30 13:14:57.597+0000 INFO [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by scheduler for time threshold [128534]:  Appending check point entry into the tx log completed
2017-10-30 13:14:57.597+0000 INFO [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by scheduler for time threshold [128534]:  Check pointing completed
2017-10-30 13:14:57.597+0000 INFO [o.n.k.i.t.l.p.LogPruningImpl] Log Rotation [48]:  Starting log pruning.
2017-10-30 13:14:57.598+0000 INFO [o.n.k.i.t.l.p.LogPruningImpl] Log Rotation [48]:  Log pruning complete.
2017-10-30 13:24:58.811+0000 ERROR [o.n.b.t.SocketTransportHandler] Fatal error occurred when handling a client connection: readAddress(..) failed: Connection timed out readAddress(..) failed: Connection timed out
io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection timed out
	at io.netty.channel.unix.Errors.newIOException(Errors.java:117)
	at io.netty.channel.unix.Errors.ioResult(Errors.java:138)
	at io.netty.channel.unix.FileDescriptor.readAddress(FileDescriptor.java:179)
	at io.netty.channel.epoll.AbstractEpollChannel.doReadBytes(AbstractEpollChannel.java:327)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:787)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)
```

In local the query is twice faster and manage to send results back. I don't think it's due to the driver though.

**Comment by ali-ince** [comment] 2017-10-30 13:46
Hi @AviAvni,

Thanks for the confirmation. However, before continuing with a release, we'll wait for a while for @juicelink to give it a try and whether anything new pops up.

We've released a snapshot version with #253 included through myget which you can access at [1.5.1-SNAPSHOT-1710300132](https://www.myget.org/feed/neo4j-driver-snapshots/package/nuget/Neo4j.Driver/1.5.1-SNAPSHOT-1710300132). Installation instructions for several platforms and tools are included on the page.

Thanks.

**Comment by ali-ince** [comment] 2017-10-30 14:51
Hi @pierre-weceipt, could you paste in your code?

**Comment by pjeannet** [comment] 2017-10-30 15:34
@ali-ince no problem : 

```c#
string uri = blob.Uri + blob.GetSharedAccessSignature(sasConstraints);            
string query = $@"USING PERIODIC COMMIT
                      LOAD CSV WITH HEADERS FROM '{uri}' AS row FIELDTERMINATOR '|'
                      WITH row WHERE row.Titre IS NOT NULL
                      MATCH (n:LegiFrance {{id:row.LegiId}})
                      MERGE (m:MotCle {{titre:row.Titre, sousTitre:coalesce(row.SousTitre,'')}})
                      WITH n, m, row
                      CALL apoc.create.addLabels(m, [row.KeywordType]) yield node  
                      MERGE (n)<-[r:MotCle]-(m)
                      SET r.occurence = row.Occurence

using (var driver = GraphDatabase.Driver("bolt://127.0.0.1",
                                         AuthTokens.Basic("neo4j", "neo4j"),
                                                     new Config() { }))

            using (var session = driver.Session())
            {
                var result = session.Run(query);
                var summary = result.Summary.Counters;
                Console.WriteLine(JsonConvert.SerializeObject(summary));
            }
```

Really basic stuff, just a bit long to run (takes around 11min to complete for the csv that timeout).

**Comment by juicelink** [comment] 2017-10-31 08:46
Hi @ali-ince ,
Tried the snapshot version.
With it, the process doesn't hang => an Unexpected end of stream exception is thrown...

It seems better, but the exception is thrown systematicly on my big request, when always with the 1.5.0-alpha-1 the error never occurs...

Same thing in sync and async

in sync error occurs here:
 [System.IO.IOException] Unexpected end of stream at Neo4j.Driver.Internal.IO.ChunkReader.ReadNextMessages(Stream messageStream)

**Comment by ali-ince** [comment] 2017-11-02 00:01
Hi @juicelink,

Can you please check your server logs for extra ordinary log entries?

Cheers.

**Comment by juicelink** [comment] 2017-11-08 09:52
HI @ali-ince ,

I got this exception server side:
2017-11-08 09:50:35.404+0000 ERROR [o.n.b.t.SocketTransportHandler] Fatal error occurred when handling a client connection: An existing connection was forcibly closed by the remote host An existing connection was forcibly closed by the remote host
java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:367)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:118)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)

client side:
Neo4j.Driver.V1.ServiceUnavailableException : Connection with the server breaks due to AggregateException: One or more errors occurred. (Unexpected end of stream.)
---- System.AggregateException : One or more errors occurred. (Unexpected end of stream.)
-------- System.IO.IOException : Unexpected end of stream.
   at Neo4j.Driver.Internal.Connector.PooledConnection.OnError(Exception error)
   at Neo4j.Driver.Internal.Connector.DelegatedConnection.<>c__DisplayClass11_0.<ReceiveOneAsync>b__0(Task t)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Neo4j.Driver.Internal.Result.ResultCursorBuilder.<>c__DisplayClass11_0.<<SetReceiveOneFunc>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Neo4j.Driver.Internal.Result.ResultCursorBuilder.<NextRecordAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Neo4j.Driver.Internal.Result.StatementResultCursor.<FetchAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Neo4j.Driver.V1.StatementResultCursorExtensions.<ToListAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Neo4J.Wrapper.Tests.DriverShould.<CanRunAsyncWriteMode>d__0.MoveNext() in D:\projects\Neo4jt\Neo4J.Wrapper.Tests\DriverShould.cs:line 17
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
----- Inner Stack Trace -----

----- Inner Stack Trace -----
   at Neo4j.Driver.Internal.IO.ChunkReader.<>c__DisplayClass12_0.<ReadNextChunkLoopAsync>b__1(Task`1 t)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Neo4j.Driver.Internal.Connector.SocketConnection.<ReceiveOneAsync>d__21.MoveNext()

**Comment by juicelink** [comment] 2017-11-08 17:15
The exception is thrown in The ChunkReader.cs after the line:
read = _downStream.Read(_buffer, _lastWritePosition, _buffer.Length - _lastWritePosition)
error thrown because of read <= 0;

What is strange is that when exception occurs, _lastWritePosition is at 16384, _buffer.Length is at 16384
So we try to read 0 bytes as we are at the end of the buffer, --> read <= 0
I'm not sure we should enter in the loop at this time.

It seems that the error occurs when _lastWritePosition is at 16384 and _lastReadPosition is at 16383

retested tagged versions:
1.5.0-alpha1 => ok
1.5.0-alpha2 and higher => ko
(Between these 2 versions ChunkReader has been rewritten)

**Comment by juicelink** [comment] 2017-11-13 12:52
- tried on a local database with same result.
- tried at home with randomly generated data and I didn't reproduce.
=> seems related to data but:
- the error never occurs at the same place
- removed properties and relations from requested nodes but same error occurs.

**Comment by ali-ince** [comment] 2017-11-14 14:43
Hi @juicelink,

The rest of this issue, apart from the fixes we've made earlier in the driver, is found to be related with memory consumption of the server. It is the server that terminates connections based on an OutOfDirectMemory exception, and it is the point where client receives an unexpected end of stream. You can tune server's memory limits through `neo4j.conf`.

We've addressed this memory pressure on the bolt server with PR #10433 and it will be part of 3.4.0 server release.

I am now closing this issue, and we'll be releasing a 1.5.1 version soon that includes driver side fixes.

Thanks,

Drivers Team

**Closed as completed** 2017-11-14 14:44 UTC

**Comment by pjeannet** [comment] 2017-11-14 15:17
Hi @ali-ince, do you include in your statement the strange `connection timeout` that I pasted before?

**Comment by ali-ince** [comment] 2017-11-15 17:15
Hi @pierre-weceipt,

As we could not be able to reproduce it, I am sorry to say that our previous reply does not apply to your issue.

We'll appreciate if you can provide us with the steps to reproduce your problem and create a new issue.

Thanks,

Drivers Team

**Comment by NivTikolski** [comment] 2017-11-21 08:21
@ali-ince 
hi, 
just want to ask when the 1.5.1 driver version will be released.

Thanks,
Niv. :)

**Comment by zhenlineo** [comment] 2017-11-21 08:57
Coming this week soon.
