### ISSUE TITLE
.NET Core Support?

### ISSUE THREAD

**Issue by amcdnl** [neo4j/neo4j-dotnet-driver#52] opened 2016-04-04 19:00 UTC
Is there any plans for [.NET Core](https://dotnet.github.io/) support?

**Comment by zhenlineo** [comment] 2016-04-06 08:07
Yes, but not the first release. We are planing targeting .net-core for Neo4j 3.1.

**Comment by amcdnl** [comment] 2016-04-06 15:46
What kind of timeline would you expect for that release?

**Comment by zhenlineo** [comment] 2016-04-07 07:55
Autumn or early winter this year according to the current plan :)

**Comment by amcdnl** [comment] 2016-04-07 12:27
@zhenlineo Thanks for feedback! Given the dotnet audience that would be using neo4j I'm surprised this isn't in sync with the release of 3.0. We are using dotnet core in our production app already and have hard dependencies on our db drivers ( neo and mongo ) that prevent us from going full x-platform.

**Comment by zhenlineo** [comment] 2016-04-14 09:51
We are considering to support dotnet core. The main concern right now is that the dotnet core is not fully release. We would like to support dotnet core after it has been released fully. 

I will keep this issue open until we fix it. Also I will keep you updated here of our work towards dotnet core support.

Thanks again for bringing this issue to us.

**Comment by jmezach** [comment] 2016-05-25 14:43
I've been working on porting this to .NET Core in my fork (https://github.com/jmezach/neo4j-dotnet-driver/tree/feature/net-core-support). Unfortunately I ran into an issue with the unit tests that fail occasionally, but that also seems to happen with the original code.

I traced the issue back to the **Neo4j.Driver.Internal.Packstream.PackStream.Unpacker** class which has a private static variable __bitConverter_ of type **BitConverterBase**. It is set inside the constructor which doesn't make much sense since its a static variable. Since its static it depends on the order in which unit tests are run whether the variable has a value or is null.

**Comment by amcdnl** [comment] 2016-05-25 14:49
@jmezach you port to RC2 yet? TBH, I'd wait that release is a huge mess.

I know @dmikov was having issues with unit tests on other projects in .NET Core. Any ideas?

**Comment by jmezach** [comment] 2016-05-25 14:54
@amcdnl I'm porting to RC2 yes. So far it was quite straightforward, except for those failing unit tests. Don't think that's a .NET Core problem though, since they also fail if I check out the original 1.1 branch and build and run those tests.

**Comment by technige** [comment] 2016-05-25 14:55
We've made this point in various places previously but it's probably worth mentioning here again.

While anyone is of course welcome to experiment with .NET Core compatibility for the driver, we will not be merging in any of these changes or providing any .NET Core support ourselves until at least after MS have made a full release.

**Comment by amcdnl** [comment] 2016-05-25 17:46
@nigelsmall I sort of agree, at this point its so much chaos its not even worth it. **However**, I do think you need a development branch for this so community members can contribute and test.... otherwise you will end up with a bunch of forks with no one in alignment.

**Comment by tugberkugurlu** [comment] 2016-05-25 18:41
Definetely agree to what @amcdnl said. We don't look for official support. Just have it on a branch and preferably release it to myget.

**Comment by technige** [comment] 2016-05-25 19:14
You may personally be happy not to expect official support but if we host such code or make any such releases, someone somewhere _will_ expect it to be supported.

I'm genuinely sorry that this is not the answer that you want but we will add this eventually and in the meantime, I suggest a group of you get together to build and maintain a community fork.

**Comment by amcdnl** [comment] 2016-05-25 19:30
@nigelsmall a development branch with some disclaimer messages is pretty standard. I think we just want somewhere to all collaborate with your team in a community format, **if thats not the attitude your team has then why even post it on github?**

@jmezach I'd be happy to work with you on this, if you want to start your own project. @cskardon is also doing some interesting stuff with [Neo4J Client](https://github.com/Readify/Neo4jClient). I think he has a dotnetcore version working but it does not do bolt ( yet ). @tugberkugurlu @dmikov

**Comment by tugberkugurlu** [comment] 2016-05-25 19:55
> You may personally be happy not to expect official support but if we host such code or make any such releases, someone somewhere will expect it to be supported.

Just release it as pre-release on myget and state on readme file that pre-release packages are not officially supported. That's how all open source projects work. They have a some sort of pre-release channel.

**Comment by dmikov** [comment] 2016-05-25 21:01
@jmezach You probably did, but I will ask anyway. Did you put the inconsistent state of tests as an issue? And I am totally for support community or official fork of the driver. Have to check neo4j-client though, how far it is. Maybe the issue is moot with this one.

**Comment by jmezach** [comment] 2016-05-26 07:12
Wow, okay, I wasn't looking to unchain a discussion on the merits of open source and whether a .NET Core port is something that's desirable. I merely wanted to figure out why the unit tests are occasionally failing regardless of whether they are running on .NET Core or not ;). But I will put in a separate issue for the failing tests as @dmikov suggested.

**Comment by amcdnl** [comment] 2016-05-26 11:43
@jmezach I msg'd you on gitter. would love to collab.

**Comment by cskardon** [comment] 2016-05-26 11:57
Hullo everyone!

Wow - some big issues raised here, well played @jmezach! 

Leaving the actual issue aside as to whether support of net core is forthcoming or not - the can of worms that appears to have been opened seems to be about a bit of a difference of opinion as to what Open Source means, and how a repo should be maintained with regards to that.

From my point of view (and I appreciate it won't match with everyone's) - Open Source means that you can look at the code, you can fork it, you can run it and you pretty much have free reign (numerous license issues aside) to do what you want. Likewise, owners of a repo/fork etc have full rights to not accept a pull, to not accept your changes, to do whatever they like. There are literally _no_ rights to anyone to expect their work will be taken in, or that an owner will do something for you.

This is awesome as it means that if something isn't working - you can just do it yourself. If the original developer dies - the project need not - etc etc - we all know this - and as we're all here we're probably roughly on the same side. 

For reference - Neo _have_ accepted pull-requests from others into their code - I know this as I've done some myself. 

Onto the suggestions -

### A Development Branch within the `neo4j/neo4j-dotnet-driver` repo

One problem with this is who maintains it - e.g.

@zhenlineo is currently maintaining this driver.

Let's imagine @jmezach does a pull request for dotnetcore (nice work buddy!). It gets into a 'dotnetcore' branch and @amcdnl and @tugberkugurlu both do more pull requests around this (PS. I'm using names of people here - to make it more real).

Now @zhenlineo needs to manage these pull requests as well - it's not being developed by Neo, but contributors are relying on Neo to publish and manage all the requests.

Now let's say _I_ do a pull and we all want it to be released ASAP. But I do my pull on Saturday morning, and unfortunately Neo allows employees to have weekends off, and maybe even holidays - they are based in socialist Sweden after all :) So we wait. But OH NOES big issue hit's Neo - all hands to battle-stations and the 'dotnetcore' branch gets forgotten about, only it doesn't. We get frustrated - "It's not good enough - why isn't it pulled in and released" etc - not good. 

Also - what happens when 2 of the main contributors want a pull in- but another disagrees - does Neo become the de facto arbiter for code it's not even actively developing? How can it make the decision?

This doesn't even come to the point of a readme, pre-release etc - and I _know_ that we probably read the readmes, I always read the examples, (but if I'm honest skip the license-y bits) - but I suspect lots of others _don't_ read them and if it's under an official repo - released with an official account - people _will_ think it is supported. 

"Just tell them it's not when they ask!" 

Good point - problem with that is they may have committed a significant amount of time to their project, and don't want to be told basically "tough luck".

"Well - that's their fault"

Again - good point - but then they bad-mouth Neo4j, Neo might lose one customer from this person - or they might go to Twitter/Blog about the experience and put off 10s/100s. As a business this is not good, and critically - Neo _is_ a business.

### A community fork maintained by community

The community gets to maintain it, and deal with bugs as and when they arrive - this seems like a super-cool goal. You're not tied to the company schedule for publishing/pulling etc - and you can get on with doing work.

This is really the point about Open Source from my POV - you _can_ do this, and you don’t need to rely on anyone else!

So to conclude - as you already have - the community fork seems the perfect way to get what you want as quickly as you want.

It's important to view Open Source from the different points of view - a business vs. a developer vs. a consumer, and work within those bounds. Even 10 years ago - you might never have had the opportunity to even argue about this - so that's progress! 

PS. Sorry this was long.

PPS. Sorry for making it longer with a PS.

**Comment by technige** [comment] 2016-05-26 12:40
Thanks @cskardon - that's a great overview.

On the subject of community collaboration (for anyone who has not already been made aware) we have chatted internally and will be creating a fork of the driver in https://github.com/neo4j-contrib - more to follow on this shortly.

**Comment by amcdnl** [comment] 2016-05-26 13:01
I tend to disagree w/ many of your points @cskardon ( although you are a rockstar and we collab a lot ;) )

### Fragmentation

Having tons of different forks and open-source projects is great, but wouldn't it be great if we could all collaborate in a somewhat official manner on the same project? Instead of duplication of work, we all put our heads together and advance it for the greater good. To me, this is what open-source is all about. 

I don't know how many times I've hunted through issues of a project to find that someone forked the project and fixed the very problem but it was never even reviewed or found 5 projects that do the same thing with different quirks but if they were all together would be awesome!

### Ownership

You are absolutely right, it is the choice of the maintainer of which to what to merge. But heres the deal, if you are a business toting 'open-source', half your work is building a community. Thats the KEY to successful OS projects. I assume that neo wants to build a great community around its products, you need to involve the community in your decisions if thats true, you need to collaborate and involve them at every step. The best thing would have been to review the code, provide feedback and create some way we can all collaborate together in a dev branch per a git-flow philosophy.

### Types of OS Projects

There are a few different types of open-source projects, those being:
- Corporate Projects, a company is supporting the project and choose to open-source
- Community Projects; a group of individuals are all collaborating around a single project or group of projects that align together.
- Individuals, A individual wrote a project to solve a specific need and wanted to share it with the community
- Pet Projects, I threw some code up as a prototype, is never mean't to be production/etc

If your in the Corp group, if you aren't going to collaborate with the community in a open platform, why even bother open-sourcing it?

### Final thoughts

I want to be clear, I NEVER expected neo to make this master branch or even contribute to this until it aligned w/ their roadmap. I simply asked for a platform given they choose to open-source this as a company to let the community collaborate in a unified manner with feedback from core team members and alignment with their vision for the future of where neo is going.

**Comment by technige** [comment] 2016-05-26 13:56
There is now a contributors repository available for experimentation with .NET Core. This can be found at -> https://github.com/neo4j-contrib/neo4j-dotnetcore-driver.

**Please note that this repository is not supported by Neo Technology.**

Closing this thread now so that activity can continue there.

**Closed as completed by technige** 2016-05-26 13:56 UTC

**Comment by jexp** [comment] 2016-06-08 22:13
Hey @amcdnl @dmikov @jmezach @tugberkugurlu 

I would have expected you would want to collaborate on and contribute to: 

https://github.com/neo4j-contrib/neo4j-dotnetcore-driver

Today someone was looking for a .Net Core variant of the driver and I hoped to be able to point them to your joint work? Please let us know if you intend to work on the .Net Core support. If not in the repo in neo4j-contrib but somewhere else, that's great too, I just would love to know where to look.

Thanks

**Comment by jgranq** [comment] 2016-11-06 12:26
Any updates on this?

**Comment by wiliambuzatto** [comment] 2018-11-12 19:05
> Any updates on this?

**Comment by ali-ince** [comment] 2018-11-12 19:20
Hi @wiliambuzatto,

The neo4j-dotnet-driver has been targeting `.NET Standard 1.3` for quite a long time now - which makes it usable .NET Core.

Thanks,

Ali

**Comment by cbhoitv-git** [comment] 2020-02-14 10:30
I found GraphQA => Cypher query converter for Java and Javascript.
But didnt find any library in .net core library which will convert GraphQA => Cypher query (Neo4j 4.0)?
